---
output: rmarkdown::github_document
editor_options: 
  chunk_output_type: console
---
```{r pkg-knitr-opts, include=FALSE}
hrbrpkghelpr::global_opts()
```

```{r badges, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::stinking_badges()
```

```{r description, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::yank_title_and_description()
```

## What's Inside The Tin

The following functions are implemented:

```{r ingredients, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::describe_ingredients()
```

## Installation

NOTE: This requires `{swiftr}`.

```{r install-ex, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::install_block()
```

## Usage

```{r lib-ex}
library(swiftspeech)

# current version
packageVersion("swiftspeech")

```

```{r ex01}
parts_of_speech("The comm wasn't working. Feeling increasingly ridiculous, he pushed the button for the 1MC channel several more times. Nothing. He opened his eyes and saw that all the lights on the panel were out. Then he turned around and saw that the lights on the refrigerator and the ovens were out. It wasn’t just the coffeemaker; the entire galley was in open revolt. Holden looked at the ship name, Rocinante, newly stenciled onto the galley wall, and said, Baby, why do you hurt me when I love you so much?")
```

## swiftspeech Metrics

```{r cloc, echo=FALSE}
cloc::cloc_pkg_md()
```

## Code of Conduct

Please note that this project is released with a Contributor Code of Conduct. 
By participating in this project you agree to abide by its terms.
